#!/bin/bash
if [ -z "$1" ]; then 
  echo usage: $0 jvmName
  exit
 fi
java -cp 'jars/*' -Djava.security.manager \
     -Djava.security.policy=dcvm.policy \
      src.cps.cvm.DistributedCVM $1 config.xml